### ISSUE TITLE
KinFu2 error: unknown error

### ISSUE THREAD

**Issue by snowface3** [mihaibujanca/dynamicfusion#48]
Hi, thanks for this project. I am hoping to get it working.

When I try to run the following command:
./build/bin/dynamicfusion data/umbrella
I get the following error:
KinFu2 error: unknow error /home/snuc/dynamicfusion/kfusion/src/device_memory.cpp::85

Any idea what this error might be?

**Comment by mihaibujanca** [comment]
Well, it's definitely a cuda error, I would check that all the linking is done correctly or run the program under cuda gdb to find out more

**Comment by snowface3** [comment]
That helped. My CUDA version was not up to date.

Now I am seeing the following error:
llvm: No such file or directory

**Comment by mihaibujanca** [comment]
Yeah, this has been reported before, I'll try to reproduce it and solve it. I do remember having the problem a while ago and unfortunately haven't documented the solution.

I *think* it may have been related to Opt so things I'd try include linking cudart, linking cuda statically or just messing around with cuda linking to Opt.

There's also a commit I had when this happened so perhaps I can check the changes from then - but I really can't remember the cause at the moment
https://github.com/mihaibujanca/dynamicfusion/commit/0447e93aa3d7401ffd775c41ed2d7c7feb0f4bbe

**Comment by mihaibujanca** [comment]
Update: i don't think it's Opt. I've cloned Opt again, built it without changing anything in the make file and linked it and it runs, so unless I've set up something else on my system that automatically links with Opt now, it's not that.

**Comment by mihaibujanca** [comment]
Reproduced, don't know how to solve it yet

**Comment by snowface3** [comment]
any luck?

**Comment by snowface3** [comment]
I was able to solve this issue, and now able to run the program. Will try to update what helped fix this- maybe it was properly installing/ linking caffee and/ or python.

**Comment by glebmak** [comment]
@snowface3 In case you remember, what solved the problem? It would be very helpful!
